export var FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export var FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export var FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export var FORGOT_PASSWORD_ERROR_AWK = 'FORGOT_PASSWORD_ERROR_AWK';
export var FORGOT_PASSWORD_MESSAGE = 'FORGOT_PASSWORD_MESSAGE';
export var FORGOT_PASSWORD_MESSAGE_AWK = 'FORGOT_PASSWORD_MESSAGE_AWK';

export var LOGIN_REQUEST = 'LOGIN_REQUEST';
export var LOGIN_REFRESH = 'LOGIN_REFRESH';
export var LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export var LOGIN_ERROR = 'LOGIN_ERROR';
export var LOGIN_ERROR_AWK = 'LOGIN_ERROR_AWK';
export var LOGIN_PASSWORD_CHALLENGE = 'LOGIN_PASSWORD_CHALLENGE';

export var LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export var LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export var LOGOUT_ERROR = 'LOGOUT_ERROR';

export var NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST';
export var NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export var NEW_PASSWORD_ERROR = 'NEW_PASSWORD_ERROR';
export var NEW_PASSWORD_ERROR_AWK = 'NEW_PASSWORD_ERROR_AWK';

export var RECOVER_PASSWORD_REQUEST = 'RECOVER_PASSWORD_REQUEST';
export var RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export var RECOVER_PASSWORD_ERROR = 'RECOVER_PASSWORD_ERROR';
export var RECOVER_PASSWORD_ERROR_AWK = 'RECOVER_PASSWORD_ERROR_AWK';
export var RECOVER_PASSWORD_MESSAGE = 'RECOVER_PASSWORD_MESSAGE';
export var RECOVER_PASSWORD_MESSAGE_AWK = 'RECOVER_PASSWORD_MESSAGE_AWK';
